# Setup
title: martian
tagline: "from red planet"
description: >-
  <h3 style="color: #FFFFFF">i'm martian</h3>i'm building things until we get to mars.<br> <br>follow me on
  <a href="https://x.com/flyme2_mars">x</a>.
url:
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: martian
  url: https://x.com/flyme2_mars
  # email: markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: UA-146052-15
